name: Publish to Itch.io

on:
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source code
        uses: actions/checkout@v3

      - name: Godot Export
        id: export
        uses: firebelley/godot-export@v7.0.0
        with:
          godot_executable_download_url: https://github.com/godotengine/godot/releases/download/4.6-stable/Godot_v4.6-stable_linux.x86_64.zip
          godot_export_templates_download_url: https://github.com/godotengine/godot/releases/download/4.6-stable/Godot_v4.6-stable_export_templates.tpz
          relative_project_path: ./
          archive_output: true
        env:
          GITHUB_TOKEN: ${{secrets.GH_TOKEN}}
      - name: Publish to Itch
        uses: Ayowel/butler-to-itch@v1.2.0
        with:
          butler_key: ${{secrets.ITCHIO_TOKEN}}
          itch_user: fabio98p
          itch_game: strange-plants
          version: ${{ github.ref_name }}
          files: "${{ steps.export.outputs.archive_directory }}/test-web.zip"